#! /bin/sh
# Manage git tokens with password encrypted files.
#
# Author: Kaj Munhoz Arfvidsson


###############
## CONSTANTS ##
###############


DATA_DIR="$HOME/.local/share/git-token"


###############
## FUNCTIONS ##
###############


usage() {
    echo 'Usage: git-token [OPTIONS] USERNAME [TOKEN]'
}

help() {
    usage
    cat << EOF
Manage git tokens with password protected files.

OPTIONS
    -h, --help          Show this help message.

    -e, --enable        Enable git credential-cache in
                        globally.

    -r, --remove        Remove token.

    -f, --force         Write over any existing token.

    -t SEC              Set git credential-cache timeout to
        --timeout=SEC   SECONDS (default "900"). Can only
                        be used with -e option.

    -d DOMAIN           Create or use a specific domain
        --domain=DOMAIN (default "https://github.com").

        --only-token    Do not save or automatically set
                        name/email.

        --recommit      Redo the last commit but using the
                        current author.

Saving a token
    The program will encrypt with gnupg a file named "adam"
    containing "xxyyzz" to the directory
    ~/.local/share/git-token. By supplying name and email
    the user can rest assured it is he/she that is the
    author as git-token will automatically set update
    git-config with name and email during token retrieval.

    > git-token adam xxyyzz

Loading a token
    The program will try to decrypt the file
    ~/.local/share/git-token/adam, print the contents, and
    call git credential to save the login credentials for a
    limited time.

    > git-token adam
EOF
}

# Return the argument at index
# > index [-]NUM [ARGS...]
index() {
    [ $# -lt 2 ] && return 1
    [ "$1" -gt 0 ] && i=$1 || i=$(($# + $1))
    [ "$i" -le 0 ] && echo "" || ( shift $i && echo "$1" )
}

# Print error and exit
# > panic [CODE] MESSAGE
panic() {
    usage
    [ $# -gt 1 ] && CODE=$1 && shift || CODE=1
    echo "Error ($CODE): $1"
    exit $CODE
}

# Climb directories to find an existing path CHILD
# > climb CHILD [ PARENT ]
climb() {
    CHILD="$1"
    PARENT="$(realpath "${2:-$PWD}")"
    [ -e "$PARENT/$CHILD" ] && echo "$PARENT" && return 0
    [ "$PARENT" = "/" ] && return 1
    climb "$CHILD" "$PARENT/.."
    return $?
}

# Assert there exist commands
# > assert_command [COMMANDS...]
assert_command() {
    for cmd in "$@"; do
        [ ! "$(command -v "$cmd")" ] && panic "Missing command \"$cmd\". Is it installed?"
    done
}

# Prompt user of something
# > prompt VAR MESSAGE
prompt() {
    VAR="$1"
    shift
    printf "$*"
    read -r "${VAR?}"
}

# Prompt user of something that shouldn't be echoed
# > prompt_secret VAR MESSAGE
prompt_secret() {
    stty -echo
    prompt "$@"
    stty echo
    printf "\n"
}

# Enable git credentials
_enable() {
    git config --global credential.helper "cache --timeout $1" || exit $?
}

# Remove user token
_remove() {
    rm -r "$DATA_DIR/${1:?}" || exit $?
}

# Approve git credential with _approve URL USERNAME PASSWORD
_approve() {
    git credential approve << EOF
url=$1
username=$2
password=$3
EOF
return $?
}

_get_last_author() {
    git log -1 --pretty=format:'%an <%ae>'
}

_recommit() {
    git commit --amend -C HEAD --reset-author
}


############
## SCRIPT ##
############


assert_command git gpg

# program arguments
REMOVE=0
ENABLE=0
FORCE=0
TIMEOUT=900
ONLY_TOKEN=0
RECOMMIT=0
USERNAME=""
TOKEN=""
NAME=""
EMAIL=""
DOMAIN="github.com"

# parse program arguments
while getopts ":herft:d:-:" OPT; do
    if [ "$OPT" = "-" ]; then
        OPT="${OPTARG%%=*}"
        OPTARG="${OPTARG#"$OPT"}"
        OPTARG="${OPTARG#=}"
    fi
    case $OPT in
        h | help ) help ; exit 0 ;;
        e | enable ) ENABLE=1 ;;
        r | remove ) REMOVE=1 ;;
        f | force ) FORCE=1 ;;
        t | timeout ) TIMEOUT="$OPTARG" ;;
        d | domain ) DOMAIN="$OPTARG" ;;
        only-token ) ONLY_TOKEN=1 ;;
        recommit ) RECOMMIT=1 ;;
        : ) panic "Missing argument to \"$OPTARG\"" ;;
        * ) panic "Unrecognized option \"$OPTARG\"" ;;
    esac
done
shift $((OPTIND-1))

# get program positional arguments
case "$#" in
    0 )
        [ "$ENABLE" -ne 0 ] && _enable "$TIMEOUT" && exit 0
        panic "Missing argument USERNAME"
        ;;
    1 )
        USERNAME=$1
        [ $ENABLE -ne 0 ] && _enable "$TIMEOUT"
        [ $REMOVE -ne 0 ] && _remove "$USERNAME" && exit 0
        ;;
    2 )
        USERNAME=$1
        TOKEN=$2
        [ $ENABLE -ne 0 ] && _enable "$TIMEOUT"
        [ $REMOVE -ne 0 ] && echo "Replacing token for \"$USERNAME\"" && _remove "$USERNAME"
        ;;
    * )
        panic "Too many arguments"
        ;;
esac

# get token from stdin if the token is, e.g. piped in
[ -p /dev/stdin ] && read -r TOKEN

USER_DIR="$DATA_DIR/$DOMAIN/$USERNAME"

if [ -n "$TOKEN" ]
then # encrypt

    if [ -d "$USER_DIR" ]
    then [ $FORCE -eq 0 ] && panic "This user already exists"
    else mkdir -p "$USER_DIR"
    fi

    if [ "$ONLY_TOKEN" -eq 0 ]
    then
        prompt NAME "Name (optional): "
        prompt EMAIL "Email (optional): "
    fi

    prompt_secret PASSWD "Password: "

    [ -n "$NAME" ] && echo "$NAME" > "$USER_DIR/name"
    [ -n "$EMAIL" ] && echo "$EMAIL" > "$USER_DIR/email"
    echo "$TOKEN" | gpg --batch --yes --passphrase "$PASSWD" -o "$USER_DIR/token" -c || panic $? "Encryption failed"

else # decrypt

    if [ ! -d "$USER_DIR" ]
    then
        NUM_CANDIDATES=$(find "$DATA_DIR" -name "$USERNAME" | wc -l)
        if [ "$NUM_CANDIDATES" -eq 0 ]
        then panic "Cannot find \"$USER_DIR\" containing the requested token."
        elif [ "$NUM_CANDIDATES" -eq 1 ]
        then
            USER_DIR="$(find "$DATA_DIR" -name "$USERNAME")"
            DOMAIN="$(basename "$(dirname "$USER_DIR")")"
            echo "Using domain \"$DOMAIN\"".
        else
            # TODO: Make this smart by suggesting domain
            panic "Cannot find \"$USERNAME\" under \"$DOMAIN\", however there are many \"$USERNAME\" in other domains. Please specify domain."
        fi
    fi

    if [ "$ONLY_TOKEN" -eq 0 ]
    then
        [ -f "$USER_DIR/name" ] && NAME="$(cat "$USER_DIR/name")" && git config --global user.name "$NAME"
        [ -f "$USER_DIR/email" ] && EMAIL="$(cat "$USER_DIR/email")" && git config --global user.email "$EMAIL"
    fi

    prompt_secret PASSWD "Password: "

    SECRET=$(gpg --batch --passphrase "$PASSWD" -d "$USER_DIR/token" 2> /dev/null)
    [ -z "$SECRET" ] && panic "Password was incorrect"
    _approve "https://$DOMAIN" "$USERNAME" "$SECRET" || panic $? "Approval failed"

    CRED_HELPER="$(index 1 "$(git config credential.helper)")"

    if [ "$CRED_HELPER" = "cache" ]
    then echo "Found token \"$SECRET\" and cached it for a limited time."
    else echo "Found token \"$SECRET\"."
    fi

    if [ "$RECOMMIT" -eq 1 ]
    then _recommit
    fi

    # Warnings:

    if [ -n "$(climb .git)" ] && [ "$ONLY_TOKEN" -eq 0 ] && [ "$(_get_last_author)" != "$NAME <$EMAIL>" ]
    then
        echo ""
        echo "WARNING: The last commit seems to have been made by someone other than you."
        echo "Is this correct? The commit was done by"
        echo "  $(_get_last_author)"
    fi

    if [ "$CRED_HELPER" != "cache" ]
    then
        echo ""
        echo "WARNING: git credential-cache is disabled, you will have to enter the token"
        echo "manually or run git-token again after enabling. Enable git credential-cache"
        echo "globally with"
        echo "> git token -e"
    fi

fi
